#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Flask-RESTful
Version  : 0.3.6
Release  : 2
URL      : https://files.pythonhosted.org/packages/20/f1/14a62bba209ae189e5c5fa33d5e0b7a4b5969488fa71fd3b8b323860bfc8/Flask-RESTful-0.3.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/20/f1/14a62bba209ae189e5c5fa33d5e0b7a4b5969488fa71fd3b8b323860bfc8/Flask-RESTful-0.3.6.tar.gz
Summary  : Simple framework for creating REST APIs
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Flask-RESTful-python3
Requires: Flask-RESTful-license
Requires: Flask-RESTful-python
Requires: Flask
Requires: Sphinx
Requires: aniso8601
Requires: blinker
Requires: nose
Requires: nosexcover
Requires: pycrypto
Requires: python-mock
Requires: pytz
Requires: six
BuildRequires : Flask
BuildRequires : aniso8601
BuildRequires : blinker
BuildRequires : buildreq-distutils3
BuildRequires : pycrypto
BuildRequires : python-mock
BuildRequires : pytz
BuildRequires : six

%description
# Running the tests
Go to main directory and type:
python2 setup.py test

%package license
Summary: license components for the Flask-RESTful package.
Group: Default

%description license
license components for the Flask-RESTful package.


%package python
Summary: python components for the Flask-RESTful package.
Group: Default
Requires: Flask-RESTful-python3
Provides: flask-restful-python

%description python
python components for the Flask-RESTful package.


%package python3
Summary: python3 components for the Flask-RESTful package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Flask-RESTful package.


%prep
%setup -q -n Flask-RESTful-0.3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536553134
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/Flask-RESTful
cp LICENSE %{buildroot}/usr/share/doc/Flask-RESTful/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/Flask-RESTful/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
